### ISSUE TITLE
Can't read MusicXML?

### ISSUE THREAD

**Issue by edom** [music-suite/musicxml2#22]
https://github.com/music-suite/musicxml2/blob/master/src/Data/Music/MusicXml/Read.hs is empty.

Or does the code for reading MusicXML live somewhere else in music-suite?

**Comment by hanshoglund** [comment]
This is a missing feature. PRs welcome.

**Comment by hanshoglund** [comment]
This repo has been merged into: https://github.com/music-suite/music-suite

Closing :)
